### ISSUE TITLE
Fail early on creator filename not writable

### ISSUE THREAD

**Issue by kelson42** [openzim/python-libzim#95]
Zimit log:
```
[DEBUG] Confirming output is writable using /output/tmpur2f0sgw
[DEBUG] Title: FFMPEG Trac Wiki
[DEBUG] Language: eng
[DEBUG] Favicon: https://trac.ffmpeg.org/chrome/common/trac.ico
[DEBUG] Found 1373 records in WARCs
No such file or directory
Traceback (most recent call last):
  File "/usr/bin/zimit", line 333, in <module>
    zimit()
  File "/usr/bin/zimit", line 265, in zimit
    return warc2zim(warc2zim_args)
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 768, in warc2zim
    return warc2zim.run()
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 439, in run
    with Creator(
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 133, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/site-packages/libzim/writer.py", line 162, in __init__
    self._creatorWrapper = _Creator(str(filename), main_page, index_language, min_chunk_size)
  File "libzim/wrapper.pyx", line 176, in libzim.wrapper.Creator.__cinit__
RuntimeError: Cannot create file /output/Trac FFMPEG Wiki 2021/1 _5180c451.zim.tmp
Exception ignored in: <function Creator.__del__ at 0x7f01b748e310>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/libzim/writer.py", line 178, in __del__
    if not self._closed:
AttributeError: 'Creator' object has no attribute '_closed'
```

See more at https://farm.youzim.it/pipeline/01816031a7d2fa9c2b0a8006/debug

**Comment by rgaudin** [comment]
The root cause is the fact that there is a forward slash in the requested ZIM name.
This should not be allowed and should fail early IMO.
The error message is a bug in the handling of the exception but this part is obsolete in libzim-next.

**Comment by rgaudin** [comment]
Just to define the scope, I think we should raise on Creator init if the target's parent is not present and/or not writable.
